[WIP] Cover ipmi
9elements/u-root pull request #15
Opened 2021-11-16 15:10 UTC by ChriMarMe

* Move structures to structure.go
* Move constants to constants.go
* Remove unused fdSet function
* Abstract syscall implementation behind interface
* Adapt implementation to new interface

2021-11-18 10:23 UTC, walterchris approved these changes
LGTM - I would change the filename.

2021-11-18 10:23 UTC, walterchris commented on pkg/ipmi/pkg_test.go
Rename the file to ipmi_devapi_test.go ?

2021-11-18 13:30 UTC, jensdrenhaus requested changes
The introduction of DevAPI interface looks super. Many dependencies get decoupled. 
I think some methods of Dev struct (which you are not use during testing) can now still being tested on its own.

2021-11-18 13:30 UTC, jensdrenhaus commented on pkg/ipmi/ipmi_devapi.go
> +type DevAPI interface {
For me, it feels wrong to call that thing API, what about Handler? 
(To be honest, I have not found the perfect naming scheme in such cases, either)

2021-11-18 13:30 UTC, jensdrenhaus commented on pkg/ipmi/pkg_test.go
+1

2021-11-22 11:57 UTC, walterchris approved these changes

2021-11-22 12:35 UTC, closed without merging

2021-11-22 12:35 UTC, ChriMarMe commented
[Open PR](https://github.com/u-root/u-root/pull/2182)