Cover/cmds/core/mv
9elements/u-root pull request #28
Opened 2021-12-06 12:41 UTC by llogen

2021-12-10 13:33 UTC, ChriMarMe requested changes
We haven't talked about it yet, so don't take this review too hard. 

In recent talks with Ron and Ryan from google we were told that using global variables is a bad pattern. This can easily cause race conditions. This was poorly communicated I guess.

I suggest you take a look at:
[https://github.com/u-root/u-root/blob/main/CONTRIBUTING.md](https://github.com/u-root/u-root/blob/main/CONTRIBUTING.md)

Also if we shall make a pair programming session, just ping me.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +
No global variables please.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	osExit(1)
No global variables please

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	osExit    = os.Exit
No global variables please

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	move(files, todir)
The move function must return an error.
```
if err := move(files, todir): err != nil {
    os.Fatal(err)
}
```

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> -		os.Exit(1)
return error to main. 
Only the main function is allowed to terminate the program even on error.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +		logFatalf("%v", err)
return the error to the main function.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +var logFatalf = log.Fatalf
No global variables.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +		got = code
mark this as well because usage of global variable.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	defer func() { osExit = oosExit }()
mark this. like comment above.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	osExit = myOsExit
like above

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +		got = 1
like above

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	logFatalf = myLogFatalf
like above

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	}
like above

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	osExit = myOsExit
like above.

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
>  	}
like above

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	osRename = myOsRename
like above

2021-12-10 13:33 UTC, ChriMarMe commented on cmds/core/mv/mv_test.go
> +	osRename = oosRename
like above

2021-12-13 11:26 UTC, ChriMarMe reviewed
This looks very neet. Just some nits :)

2021-12-13 11:26 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	err := move(files, todir)
`if err := move(files, todir); err != nil {...}`

2021-12-13 11:26 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +		}
usage does not need to return an error. If usage is triggered just os.Exit(1) afterwards regardless

2021-12-13 11:26 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	return errOsExit
usage does not need to return an error. See comment below.

2021-12-13 11:26 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +		return errOsExit
Take the Printf message and return it as fmt.Errorf()

2021-12-13 11:26 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	return nil
`return mv(files, todir)`

2021-12-13 11:28 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	return errOsExit
maybe below was wrong. it appears above :D

2021-12-13 11:49 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	var todir bool
I just wondered: Do you need to pass this boolean to the move function, or can it be declared in the move function as well without changing the functions behavior?

2021-12-20 07:52 UTC, ChriMarMe commented on cmds/core/mv/mv.go
> +	if err := move(files); err != nil {
Lassen sich diese zwei Zeilen kombinieren? :)

2021-12-21 15:02 UTC, MDr164 requested changes

2021-12-21 15:02 UTC, MDr164 commented on cmds/core/mv/mv_test.go
> +			t.Errorf("Expected err: %s, got: %s", err.Error(), testTable[0].err)
Usually instead of extracting the error string using err.Error() and displaying that via %s you just use %v and display the error objects text like that. The reason behind that is, that err.Error() on an error which is nil would cause a nil pointer dereference which in this case can't happen because of the previous check but it's a good pattern to do anyways as %v can also properly display nil objects

2021-12-22 08:39 UTC, MDr164 approved these changes

2022-01-10 10:07 UTC, closed without merging