WIP: Add tests for /pkg/memio
9elements/u-root pull request #3
Opened 2021-11-10 15:59 UTC by depate

- /pkg/memio: Add error checking
- /pkg/memio: Add coverage for String conversion
- /pkg/memio: Add coverage of seek.go
- /pkg/memio: Describe structs for testing
- /pkg/memio: Add testing for error case

2021-11-23 12:09 UTC, ChriMarMe approved these changes

2021-11-23 12:10 UTC, ChriMarMe requested changes
Have a look at the failing integration test. Something is not quite right.

2021-11-23 15:28 UTC, llogen commented on pkg/memio/memio_test.go
> +			tmpFile, err := ioutil.TempFile("", "io_test")
Zeile 74-85 könnte außerhalb der for loop leben.

2021-11-23 15:32 UTC, llogen commented on pkg/memio/memio_test.go
> +			tmpFile, err := ioutil.TempFile("", "io_test")
Zeile 144-155 wie oben.

2021-11-23 15:37 UTC, llogen commented on pkg/memio/memio_test.go
> +func ExampleRead() {
Zeile 230-243 aus meiner Sicht überflüssig.

2021-11-24 08:06 UTC, llogen reviewed
Looks good to me, i just noticed some structure issues. I don't know if my notes are relevant.

2021-11-24 08:06 UTC, llogen commented on pkg/memio/ports_test.go
> +// TestIoplErr tests the error evaluation of ArchIn and ArchOut,
Zeile 217-242 wie oben?

2021-11-24 08:06 UTC, llogen commented on pkg/memio/seek_test.go
> +			tmpFile, err := ioutil.TempFile("", "seek_test")
Zeile 19-26 kann meines Erachtens wieder raus aus der for loop.

2021-11-24 09:49 UTC, depate commented on pkg/memio/memio_test.go
> +func ExampleRead() {
Die waren schon da. 

`func ExampleXxx` ist ein [Feature](https://pkg.go.dev/testing#hdr-Examples) von `testing` das wir bisher nicht nutzen. FYI: @MDr164  
Es fehlt hier der Output Kommentar um irgendetwas zu bewirken. 

Da es schon da war, würde ich es drin lassen.

2021-11-24 09:49 UTC, depate commented on pkg/memio/memio_test.go
> +			tmpFile, err := ioutil.TempFile("", "io_test")
Ack

2021-11-24 09:49 UTC, depate commented on pkg/memio/memio_test.go
> +			tmpFile, err := ioutil.TempFile("", "io_test")
Ack

2021-11-24 10:33 UTC, depate commented
@ChriMarMe solving llogens comments the integrations tests are now successful. :shrug: Seems to be the looping was the culprit

2021-11-25 12:49 UTC, MDr164 requested changes

2021-11-25 12:49 UTC, MDr164 commented on pkg/memio/memio_test.go
> +// Copyright 2012-2019 the u-root Authors. All rights reserved
nit: It's already 2021 actually

2021-11-25 12:49 UTC, MDr164 commented on pkg/memio/memio_test.go
> +		t.Error(err)
Make error messages a bit more verbose e.g. `t.Errorf("Failed creating tempfile: %v", err)`

2021-11-25 12:49 UTC, MDr164 commented on pkg/memio/memio_test.go
> +
nit: remove blank line

2021-11-25 12:49 UTC, MDr164 commented on pkg/memio/memio_test.go
> +		t.Run(fmt.Sprintf(tt.name), func(t *testing.T) {
I guess fmt.Sprintf around tt.name is redundant here

2021-11-25 12:49 UTC, MDr164 commented on pkg/memio/memio_test.go
> +			tt.err = "This is a dummy error"
nit: Error strings in Go should always start with a small letter in case they are returned and not directly printed

2022-01-05 12:32 UTC, closed without merging