Cover/cmds/core/ls
9elements/u-root pull request #32
Opened 2021-12-14 14:04 UTC by llogen

Refactored ls and added tests.

2021-12-14 14:13 UTC, MDr164 requested changes

2021-12-14 14:13 UTC, MDr164 commented on cmds/core/ls/ls.go
> +			return fmt.Errorf("%v", err)
You can simply return the error is you don't add any information via Errorf to is. Doing a %v simply takes the raw contents of the error without modification and wraps it in a new error object with the same contents.

2021-12-14 14:13 UTC, MDr164 commented on cmds/core/ls/ls.go
>  		// Soft error. Useful when a permissions are insufficient to
No longer a "soft error" in my opinion as you now return the error instead of nil, so maybe fixup this comment as well.

2021-12-14 14:13 UTC, MDr164 commented on cmds/core/ls/ls.go
> +		os.Exit(1)
os.Exit(1) indicates an error has occured. But simply calling help and printing out values isn't erroneous behavior so os.Exit(0) would be more suitable here.

2021-12-14 14:17 UTC, ChriMarMe commented
```
gotest.go:165: Test github.com/u-root/u-root/cmds/core/ls.TestLargeDevNumber failed:
        === RUN   TestLargeDevNumber
            ls_linux_test.go:42: exit status 2
        --- FAIL: TestLargeDevNumber (0.08s)
```

Also the integration test fails.

2021-12-14 14:20 UTC, llogen commented
> ```
> gotest.go:165: Test github.com/u-root/u-root/cmds/core/ls.TestLargeDevNumber failed:
>         === RUN   TestLargeDevNumber
>             ls_linux_test.go:42: exit status 2
>         --- FAIL: TestLargeDevNumber (0.08s)
> ```
> 
> Also the integration test fails.

The integration test requires root.

2021-12-14 15:02 UTC, MDr164 commented
> > ```
> > gotest.go:165: Test github.com/u-root/u-root/cmds/core/ls.TestLargeDevNumber failed:
> >         === RUN   TestLargeDevNumber
> >             ls_linux_test.go:42: exit status 2
> >         --- FAIL: TestLargeDevNumber (0.08s)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also the integration test fails.
> 
> The integration test requires root privilegios.

The integration tests are run with root privileges actually but it's weird that only amd64 fails while the other archs don't

2021-12-14 15:55 UTC, llogen commented
> > > ```
> > > gotest.go:165: Test github.com/u-root/u-root/cmds/core/ls.TestLargeDevNumber failed:
> > >         === RUN   TestLargeDevNumber
> > >             ls_linux_test.go:42: exit status 2
> > >         --- FAIL: TestLargeDevNumber (0.08s)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also the integration test fails.
> > 
> > 
> > The integration test requires root privilegios.
> 
> The integration tests are run with root privileges actually but it's weird that only amd64 fails while the other archs don't

The search for the (exit status 2) is overwhelming me.

2021-12-21 14:47 UTC, MDr164 submitted a review, later dismissed

2021-12-21 14:50 UTC, MDr164 commented
> > > > ```
> > > > gotest.go:165: Test github.com/u-root/u-root/cmds/core/ls.TestLargeDevNumber failed:
> > > >         === RUN   TestLargeDevNumber
> > > >             ls_linux_test.go:42: exit status 2
> > > >         --- FAIL: TestLargeDevNumber (0.08s)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Also the integration test fails.
> > > 
> > > 
> > > The integration test requires root privilegios.
> > 
> > 
> > The integration tests are run with root privileges actually but it's weird that only amd64 fails while the other archs don't
> 
> The search for the (exit status 2) is overwhelming me.

Exit code 2 can mean several things, in this case it's probably due to memory exhaustion. So maybe the error was expected and is only wrongfully reported as unexpected in the test?

2022-01-04 09:14 UTC, llogen commented
I found and fixed the issue of the failing amd integration test.

2022-02-15 11:47 UTC, llogen commented
I reopened this PR because cmds/core/ls seems to have trouble with the amd64 integration test. This often come up within other PR's. I can't find the issue though.

2022-02-28 08:41 UTC, closed without merging