cmds/core/ping
9elements/u-root pull request #34
Opened 2021-12-20 15:34 UTC by llogen

Refactored ping.go and added tests for it.

Signed-off-by: llogen <christophlange95@googlemail.com>

2021-12-20 15:42 UTC, llogen commented
Ein Test failed noch auf Grund einer Hardgecodeten IP, da kümmere ich mich morgen früh drum.

2021-12-21 15:10 UTC, MDr164 requested changes

2021-12-21 15:10 UTC, MDr164 commented on cmds/core/ping/ping.go
> +		os.Exit(0)
I guess this case can be os.Exit(1) as the user did not provide enough arguments, causing the program to bail out and display proper usage.

2021-12-21 15:10 UTC, MDr164 commented on cmds/core/ping/ping.go
> +		log.Fatalf("%v", err)
Should be log.Fatal(err)

2021-12-21 15:10 UTC, MDr164 commented on cmds/core/ping/ping_test.go
> +// Copyright 2015-2017 the u-root Authors. All rights reserved
2021

2021-12-21 15:10 UTC, MDr164 commented on cmds/core/ping/ping_test.go
> +
blank line

2022-01-04 12:09 UTC, ChriMarMe commented on cmds/core/ping/ping_test.go
> +			if err != nil {
in eine zeile :)

2022-01-04 12:47 UTC, walterchris commented on cmds/core/ping/ping_test.go
> +			want:       fmt.Errorf("ping failed: %v", fmt.Errorf("net.Dial(%v %v) failed: %v", "ip4:icmp", "", "dial ip4:icmp: missing address")),
Why all these Errorf? It's static here and will not change will it?

2022-01-04 13:36 UTC, llogen commented on cmds/core/ping/ping_test.go
> +			want:       fmt.Errorf("ping failed: %v", fmt.Errorf("net.Dial(%v %v) failed: %v", "ip4:icmp", "", "dial ip4:icmp: missing address")),
No it won't

2022-01-10 11:44 UTC, closed without merging