Cover/cmds/core/mkdir
9elements/u-root pull request #36
Opened 2021-12-21 11:08 UTC by llogen

Refactored mkdir.go and refactored tests in mkdir_test.go

Signed-off-by: llogen <christophlange95@googlemail.com>

2021-12-21 14:44 UTC, MDr164 requested changes

2021-12-21 14:44 UTC, MDr164 commented on cmds/core/mkdir/mkdir.go
> +			return fmt.Errorf("invalid mode '%s'", *mode)
nit: Instead of writing '%s' you can use %q which formats a string in quotes

2021-12-21 14:44 UTC, MDr164 commented on cmds/core/mkdir/mkdir.go
>  			os.Chmod(name, createMode)
I know there was no error checking here before but when changing the mode the error should be checked in my opinion.

2021-12-21 14:44 UTC, MDr164 commented on cmds/core/mkdir/mkdir.go
> +		log.Fatalf("%v", err)
If you just want to log the error and terminate you could simplify this by writing log.Fatal(err)

2021-12-22 07:32 UTC, llogen commented on cmds/core/mkdir/mkdir.go
> +			return fmt.Errorf("invalid mode '%s'", *mode)
thank you for that tip :)

2021-12-22 07:44 UTC, llogen commented on cmds/core/mkdir/mkdir.go
>  			os.Chmod(name, createMode)
But what could go wrong except invalid file and wrong mode, which is both catched before. I could add it but i couldn't test it.

2021-12-22 08:21 UTC, MDr164 commented on cmds/core/mkdir/mkdir.go
>  			os.Chmod(name, createMode)
I missed the part where f got assigned the os.Mkdir/MkdirAll function so you're right, the only error that could possibly occur here, which is of type *PathError is not able to occur because error checking is done in line 73. So the only thing that could happen is a linter complaining but as the code has been here like this before it should be good to go.

2022-01-04 10:17 UTC, MDr164 requested changes

2022-01-04 10:17 UTC, MDr164 commented on cmds/core/mkdir/mkdir_test.go
>  			if err != nil {
`if err := mkdir(tt.args); err != nil {`

2022-01-04 10:17 UTC, MDr164 commented on cmds/core/mkdir/mkdir_test.go
> +					if err == nil {
`if stat, err := os.Stat(name); err == nil {` can be used here as `stat` is only used within the context of the if-condition

2022-01-10 10:00 UTC, closed without merging