Cover/cmds/core/dmesg
9elements/u-root pull request #38
Opened 2021-12-22 09:03 UTC by llogen

Refactored dmesg.go and added tests for it.

Signed-off-by: llogen <christophlange95@googlemail.com>

2021-12-22 09:49 UTC, MDr164 requested changes

2021-12-22 09:49 UTC, MDr164 commented on cmds/core/dmesg/dmesg.go
> -//go:build !plan9 && !windows
dmesg won't work on plan9 or windows so it would be reasonable to keep the build conditions

2021-12-22 09:49 UTC, MDr164 commented on cmds/core/dmesg/dmesg_test.go
> +			expErr:    fmt.Errorf("cannot specify both -clear and -read-clear"),
Why do you expect an error here if only one of the flags is set?

2021-12-22 09:49 UTC, MDr164 commented on cmds/core/dmesg/dmesg_test.go
> +			expErr:    fmt.Errorf("cannot specify both -clear and -read-clear"),
Same as above

2021-12-22 09:53 UTC, llogen commented on cmds/core/dmesg/dmesg_test.go
> +			expErr:    fmt.Errorf("cannot specify both -clear and -read-clear"),
oops, it is an copypaste mistake

2021-12-22 09:54 UTC, llogen commented on cmds/core/dmesg/dmesg.go
> -//go:build !plan9 && !windows
Thank you!

2022-01-04 10:08 UTC, MDr164 requested changes

2022-01-04 10:08 UTC, MDr164 commented on cmds/core/dmesg/dmesg.go
> +// go:build !plan9 && !windows
I think it was meant to not have a space after `//` as seem here: https://pkg.go.dev/cmd/go#hdr-Build_constraints

2022-01-04 10:08 UTC, MDr164 commented on cmds/core/dmesg/dmesg_test.go
> +			if err != nil {
`if err := dmesg(buf); err != nil {`

2022-01-04 11:39 UTC, llogen commented on cmds/core/dmesg/dmesg.go
> +// go:build !plan9 && !windows
thank you for that catch!

2022-01-05 07:54 UTC, jensdrenhaus commented
Is the loss of coverage due to the codecov report problem?

2022-01-05 08:35 UTC, llogen commented
> Is the loss of coverage due to the codecov report problem?

Jep

2022-01-10 09:51 UTC, closed without merging