Cover/cmds/core/mknod
9elements/u-root pull request #41
Opened 2022-01-03 11:39 UTC by llogen

Refactored mknod files and adapted tests.

Signed-off-by: llogen <christophlange95@googlemail.com>

2022-01-03 14:43 UTC, MDr164 requested changes

2022-01-04 10:01 UTC, MDr164 requested changes

2022-01-04 10:01 UTC, MDr164 commented on cmds/core/mknod/mknod_linux_test.go
> +			if err != nil {
`if err := mknod(tt.input); err != nil {`

2022-01-04 12:03 UTC, walterchris requested changes
https://github.com/u-root/u-root/blob/main/CONTRIBUTING.md#unit-test-checks

2022-01-05 07:51 UTC, jensdrenhaus reviewed
I am uncertain if it makes sense to check for concrete error messages in the tests here. 
Basically, you should just check for an error or a certain type. 
If someone changes the wording of the error string, the test will not pass anymore.

2022-01-10 09:46 UTC, closed without merging