Cover/pkg/pci
9elements/u-root pull request #46
Opened 2022-01-11 09:55 UTC by llogen

Added tests for the package pkg/pci.

2022-01-11 10:08 UTC, llogen commented
Does someone know why the 'Go / linters' check failes?

2022-01-17 12:09 UTC, MDr164 requested changes
The comments I made mention smaller issues that occur several times more in this PR, but I don't want to spam this thread too much.

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/bits_test.go
> +				t.Errorf("Control bits for '%#x': got: '%s', want: '%s'", tt.control, got, tt.want)
You can use `%q` instead of `'%s'` here as well. I always look up the different format values using this cheat sheet: https://yourbasic.org/golang/fmt-printf-reference-cheat-sheet/

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/bits_test.go
> +				t.Errorf("Control bits for '%#x': got: '%s', want: '%s'", tt.status, got, tt.want)
`%q`

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/bits_test.go
> +		// {
Why is this test currently commented out?

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/bits_test.go
> +				t.Errorf("BAR %s: got error: '%s', want '%s'", tt.bar, err, tt.err)
`%q`

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/bits_test.go
> +				t.Errorf("BAR %s: got: 'nil', want '%s'", tt.bar, tt.err)
`%q`

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/bits_test.go
> +				t.Errorf("BAR %s: got: '%s', want: '%s'", tt.bar, got, tt.want)
`%q`

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/devices_test.go
> +					t.Errorf("Buffer contains = '%s', want: '%s'", writeBuf.String(), tt.want)
`%q`

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/devices_test.go
> +				t.Errorf("Vendor mismatch, got: '%s', want: '%s'\n", VendorNameGot, tt.VendorNameWant)
`%q`

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/devices_test.go
> +				t.Errorf("Device mismatch, got: '%s', want: '%s'\n", DeviceNameGot, tt.DeviceNameWant)
`q%`

In addition I'm not sure if those error strings currently resemble what Google wants to see. There was something about their "new" way to format things on a pull upstream: https://github.com/u-root/u-root/pull/2193/files#r785002620

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/devices_test.go
> +	dir, err := os.MkdirTemp(os.TempDir(), "hi.dir")
You can use the `dir := t.TempDir()` method here instead so you don't need to care about creating the dir manually

2022-01-17 12:09 UTC, MDr164 commented on pkg/pci/devices_test.go
> +	f.Write(configBytes)
Check the error here

2022-01-17 12:43 UTC, llogen commented on pkg/pci/devices_test.go
> +				t.Errorf("Device mismatch, got: '%s', want: '%s'\n", DeviceNameGot, tt.DeviceNameWant)
I just leave it like that and see what they say about it.

2022-01-25 06:10 UTC, ChriMarMe requested changes
Sehr sehr nice soweit.

Noch die beiden Stellen und dann is fertig.

2022-01-25 06:10 UTC, ChriMarMe commented on pkg/pci/bits_test.go
> +				t.Errorf("BAR %s: got: %q, want: %q", tt.bar, got, tt.want)
Hier stimmt das Error format noch nicht.

2022-01-25 06:10 UTC, ChriMarMe commented on pkg/pci/lookup_test.go
> +				t.Errorf("Device mismatch, got: '%s', want: '%s'\n", DeviceNameGot, tt.DeviceNameWant)
Error format

2022-01-25 07:29 UTC, ChriMarMe commented on pkg/pci/devices_test.go
> +				t.Errorf("Device mismatch, got: %q, want: %q\n", DeviceNameGot, tt.DeviceNameWant)
Hier auch

2022-01-25 07:46 UTC, llogen commented on pkg/pci/bits_test.go
> +				t.Errorf("BAR %s: got: %q, want: %q", tt.bar, got, tt.want)
Das ist nicht der direkte Return der Funktion, daher keine direkte Referenzierung auf die Funktion im Errorf.

2022-01-25 07:46 UTC, llogen commented on pkg/pci/lookup_test.go
> +				t.Errorf("Device mismatch, got: '%s', want: '%s'\n", DeviceNameGot, tt.DeviceNameWant)
Das ist nicht der direkte Return der Funktion, daher keine direkte Referenzierung auf die Funktion im Errorf.

2022-01-25 07:46 UTC, llogen commented on pkg/pci/devices_test.go
> +				t.Errorf("Device mismatch, got: %q, want: %q\n", DeviceNameGot, tt.DeviceNameWant)
Das ist nicht der direkte Return der Funktion, daher keine direkte Referenzierung auf die Funktion im Errorf.

2022-01-26 09:17 UTC, closed without merging