Cover/smbiosPart2
9elements/u-root pull request #49
Opened 2022-01-18 16:35 UTC by walterchris

2022-01-25 05:53 UTC, ChriMarMe commented on pkg/smbios/struct_parser_test.go
> +			// TODO: Manual checking if it has been parsed correctly.
Was that ToDo a reminder?

2022-01-25 05:53 UTC, ChriMarMe approved these changes
LGTM. Schau dir nur den einen Kommentar an :)

2022-01-25 17:43 UTC, walterchris commented on pkg/smbios/struct_parser_test.go
> +			// TODO: Manual checking if it has been parsed correctly.
Oh yeah - need to resolve this :) The questions is, is the check sufficient or do we need to check all fields manually?

2022-01-26 08:29 UTC, llogen requested changes
I just found nits. Lgtm!

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/info_linux_test.go
> +		t.Errorf("FromSysfs() = '%q', '%v', want nil", info, err)
'%q' double quoted? I think %q should be enough

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/info_test.go
> +		t.Errorf("GetSystemInfo() = '%q', '%v'", systeminfo, err)
same

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/struct_parser_test.go
> +			t.Errorf("TestParseStructUnsupported : parseStruct() = %d, '%v' want: '%s'", off, err, want)
same

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/type17_memory_device_test.go
> +				t.Errorf("MemDevFormFactor.String() = '%s', want '%s'", got, tt.want)
%q

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/type17_memory_device_test.go
> +				t.Errorf("MemDevTechnology.String() = '%s', want '%s'", got, tt.want)
%q

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/type17_memory_device_test.go
> +				t.Errorf("MemDevTypeDetail.String() = '%s', want '%s'", got, tt.want)
%q

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/type17_memory_device_test.go
> +				t.Errorf("MemoryDeviceOperatingModeCapability.String() = '%s', want '%s'", got, tt.want)
%q

2022-01-26 08:29 UTC, llogen commented on pkg/smbios/type17_memory_device_test.go
> +				t.Errorf("MemoryDevice.String() = '%s', want '%s'", got, tt.want)
%q

2022-01-26 08:42 UTC, llogen approved these changes

2022-01-26 08:55 UTC, closed without merging