cmds/exp/pox: Add tests.
9elements/u-root pull request #53
Opened 2022-02-01 08:45 UTC by llogen

Refactored pox.go and pox_test.go.

Signed-off-by: llogen <christophlange95@googlemail.com>

2022-02-16 10:14 UTC, MDr164 requested changes

2022-02-16 10:14 UTC, MDr164 commented on cmds/exp/pox/pox_vm_test.go
> +func TestIntegrationIPMI(t *testing.T) {
IPMI?

2022-02-16 10:14 UTC, MDr164 commented on cmds/exp/pox/pox_vm_test.go
> +	testutil.SkipIfNotRoot(t)
Did we decide on how or if we want to use this still? I wasn't sure if we said something about that.

2022-02-16 10:14 UTC, MDr164 commented on cmds/exp/pox/pox_vm_test.go
> +	if _, err := os.Create("/bin/bash"); err != nil {
If we don't assign the newly created `*File` to a variable it will probably remain open. I don't really know what happens if that file is being deleted while there still exists a file descriptor for it. I suppose garbage collection might take care of it but it might be cleaner to assign it and call `Close()` on it immediately. I'd like another reviewers opinion on that.

2022-02-28 09:20 UTC, llogen commented on cmds/exp/pox/pox_vm_test.go
> +	testutil.SkipIfNotRoot(t)
If not used the tmp files cannot be created ...

2022-02-28 09:28 UTC, llogen commented on cmds/exp/pox/pox_vm_test.go
> +	testutil.SkipIfNotRoot(t)
Or do i use the VM test wrong?

2022-02-28 11:41 UTC, closed without merging