Cover/cmds/exp/rush: Add tests.
9elements/u-root pull request #72
Opened 2022-03-02 09:41 UTC by llogen

Refactored parse.go && rush.go. Also added tests for parse.go.

Signed-off-by: llogen <christoph.lange@9elements.com>

2022-03-02 12:34 UTC, walterchris requested changes

2022-03-02 12:34 UTC, walterchris commented on cmds/exp/rush/rush_test.go
> +// func TestRush(t *testing.T) {
This one is commented out?

2022-03-02 12:36 UTC, walterchris commented on cmds/exp/rush/rush_test.go
> +// func TestRush(t *testing.T) {
Whoops.. did not see the WIP

2022-03-04 15:58 UTC, MDr164 commented
We actually planned on removing this command altogether in favor of exp/gosh but there was no statement on the 'when'

2022-03-15 10:36 UTC, closed without merging