Coverage pkg/recovery
9elements/u-root pull request #8
Opened 2021-11-11 13:10 UTC by MDr164

Signed-off-by: Marvin Drees <marvin.drees@9elements.com>

2021-11-17 16:39 UTC, depate requested changes
if conditions...

2021-11-17 16:39 UTC, depate commented on pkg/recovery/securerecoverer_test.go
> +			if tt.name == "recover reboot" {
Seriously?! ;-)

2021-11-17 17:05 UTC, jensdrenhaus commented on pkg/recovery/securerecoverer_test.go
> +			if tt.name == "recover reboot" {
+10000

2021-11-17 17:10 UTC, depate submitted a review, later dismissed
Smells good to me

2021-11-17 17:11 UTC, jensdrenhaus submitted a review, later dismissed

2021-11-23 11:42 UTC, ChriMarMe approved these changes

2021-11-23 11:42 UTC, ChriMarMe requested changes
Remove changes to go.yml

And rebase

2021-11-24 08:54 UTC, llogen reviewed
Nothing to add.

2021-12-17 14:08 UTC, ChriMarMe submitted a review, later dismissed

2021-12-22 10:08 UTC, closed without merging